# Generated by Django 4.1.1 on 2023-01-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolormodel',
            name='Colour',
            field=models.CharField(choices=[('1', 'red'), ('2', 'blue'), ('3', 'green'), ('4', 'black')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='productmainmodel',
            name='Quality',
            field=models.CharField(choices=[('1', 'high'), ('2', 'Low'), ('3', 'medium')], default='2', max_length=50),
        ),
        migrations.AlterField(
            model_name='productmainmodel',
            name='Size',
            field=models.IntegerField(choices=[('1', '10'), ('2', '20'), ('3', '30')], default='1'),
        ),
    ]
