# Generated by Django 4.1.1 on 2023-01-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_alter_productcolormodel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='Size',
            field=models.CharField(choices=[('1', '10'), ('2', '20'), ('3', '30')], default='1', max_length=50),
        ),
    ]
